{
 "title": "qbtlib.sh",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "qbthost",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"qbt\",\n    tag: \"host\"\n)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Client's software",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"qbt\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] =~ /^${qbthost:regex}$/ )\n  |> filter(fn: (r) => r[\"stat\"] == \"clients\" )\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> sort(columns: [\"value\"])\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"qbt\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] =~ /^${qbthost:regex}$/ )\n  |> filter(fn: (r) => r[\"stat\"] == \"countries\" )\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> sort(columns: [\"value\"])\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "Speed and connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"qbt\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] =~ /^${qbthost:regex}$/ )\n  |> filter(fn: (r) => r[\"_measurement\"] == \"connections\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n"
    },
    {
     "query": "from(bucket: \"qbt\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] =~ /^${qbthost:regex}$/ )\n  |> filter(fn: (r) => r[\"stat\"] == \"speed\" )\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"_field\")"
    }
   ]
  },
  {
   "title": "States",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"qbt\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] =~ /^${qbthost:regex}$/ )\n  |> filter(fn: (r) => r[\"stat\"] == \"state\" )\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> sort(columns: [\"value\"])\n  |> yield(name: \"_field\")"
    }
   ]
  }
 ]
}